server:
  port: 8181

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty


  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: user
    password: password
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true
  kafka:
    producer:
      bootstrap-servers: 192.168.1.100:9092

account:
  branch: 0001
  bank: 121
  topic:
    event: account
    transaction: accountTransaction

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    poc.eventchain: DEBUG
    com.example: DEBUG
  file: app.log
  